### ISSUE TITLE
can't open file '/home/xxx/GeneralExplorationPolicy/mars-explorer/tests/test.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by Zora225** [dimikout3/MarsExplorer#1]
can't open file '/home/xxx/GeneralExplorationPolicy/mars-explorer/tests/test.py': [Errno 2] No such file or directory

**Comment by dimikout3** [comment]
Hello @jiayouya , it seems that the file was missing. I pushed the corresponding file there. Please pull the repo and try again,  it will work. Let me know if you face any other issues.

**Comment by Zora225** [comment]
OK！Thank you for your reply.
