### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/home/dkoutras/Documents/IROS2021/42x42/params.json'

### ISSUE THREAD

**Issue by Zora225** [dimikout3/MarsExplorer#2]
when I executed
 "python non-learning/frontierCostExploration.py"

**Comment by dimikout3** [comment]
Inside the python script (non-learning/frontierCostExploration.py) you will see a variable CONF_PATH, that is where you have to define your params.json file required to run non-learning approaches. I will upload a reference file asap

**Comment by dimikout3** [comment]
@jiayouya  please try running again the command and let me know about your progress

**Comment by Zora225** [comment]
It works, thank you.

> Inside the python script (non-learning/frontierCostExploration.py) you will see a variable CONF_PATH, that is where you have to define your params.json file required to run non-learning approaches. I will upload a reference file asap

The problem was solved.
