### ISSUE TITLE
Missing Image

### ISSUE THREAD

**Issue by 010JIN** [dimikout3/MarsExplorer#4]
HI：
when I set all the environments well, and run the test.py, there is an error.
<img width="852" alt="截屏2022-09-03 12 38 41" src="https://user-images.githubusercontent.com/105320955/188268702-8bace78f-acbc-41fa-bb09-88b455f6e066.png">
Can u help me to work it out?
Much thanks.

**Comment by dimikout3** [comment]
Hi! Please check if the relevant file is in the corresponding directory.

**Comment by 010JIN** [comment]
> 
Hi, really thanks for replying to me so soon.
I check the directory and replace it with an absolute path, but it still shows a keyerror.
<img width="1115" alt="截屏2022-09-04 10 40 58" src="https://user-images.githubusercontent.com/105320955/188307379-26dc33db-284b-4f98-bb60-d9dfd21a7953.png">
Can you help me to figure it out?
btw:
I am a college student who wants to implement your MarsExplorer environment and try something new(like chage the reward function or add some dynamic obstructions or change the RL algorithm for example using PPO+AGE/DQN+DDPG), I will really appreciate it with your generous help . You can feel free to contact me on whats app(+44 07536134585) or email me(j.lin26@lancaster.ac.uk）， thanks again !!!:)

**Comment by dimikout3** [comment]
Glad to see people working on our project! I would like to be as helpful as possible. The error that you might encounter is related to the file on your absolute path, you should have something like "img.png" or "img.jpg" (depending on the file format of the image) not simple "img".

**Comment by 010JIN** [comment]
> 

<img width="662" alt="截屏2022-09-05 15 01 50" src="https://user-images.githubusercontent.com/105320955/188466894-40e92b7e-3d48-4e2c-bba6-c5cbc1005071.png">

Thank you! It has already can be run by the test.py
